version: "3.9"
services:
  jongyoon_jh:
    build: .
    # runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    tty: true
    restart: always
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # or device number (e.g. 0) to allow a single gpu
    ports:
      - "30188:8888"  # port for JupyterLab (or JupyterNotebook)
      - "30122:22"  # port for ssh
    volumes:
      - ${BASE_DIR}/jongyoon_jh/.cache:$HOME/.cache
      - ${BASE_DIR}/jongyoon_jh/docker_volume:/workspace
