version: "3.9"
services:
  jongyoon:
    build: .
    # runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    tty: true
    restart: always
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # or device number (e.g. 0) to allow a single gpu
    ports:
      - "30088:8888"  # port for JupyterLab (or JupyterNotebook)
      - "30022:22"  # port for ssh
    volumes:
      - ${SSD_DIR}/jongyoon/.cache:/root/.cache
      - ${SSD_DIR}/jongyoon/.virtualenvs:/root/.virtualenvs
      - ${SSD_DIR}/jongyoon/docker_volume:/workspace
      - ${HDD_DIR}/jongyoon:/data
